### ISSUE TITLE
Dev command

### ISSUE THREAD

**Issue by jacekelgda** [jacekelgda/realtime-polling#10]
When I run `dev` command I got an error.
If there is more setup to be made please update readme. Seems to be related to webpack setup.

<img width="843" alt="screenshot 2017-11-29 09 32 57" src="https://user-images.githubusercontent.com/1003372/33365459-962ac5c8-d4e8-11e7-8ae7-be9495166c66.png">

**Comment by hbarroso** [comment]
Already being address in the https://github.com/jacekelgda/realtime-polling/pull/11
